name: rfc_processing
channels:
  - conda-forge
  - anaconda
  # - defaults
dependencies:
  - simplekml ==1.3.6
  - gdal ==3.6.3
  - click ==8.1.3
  - pyyaml ==6.0.0
  - rasterio ==1.3.6
  - setuptools ==75.1.0
  - glob2 ==0.7
  - geopandas ==0.12.2
  - matplotlib ==3.7.1
  - h5py ==3.8.0
  - appdirs ==1.4.4
  - future ==0.18.3
  - pystac ==1.7.1
  - sentinelsat ==1.2.1
  - python-dotenv ==1.0.0
  - requests ==2.28.2
  - urllib3 ==1.26.15
  - sqlite ==3.40.0
  - descartes ==1.1.0
  - rioxarray ==0.14.0
  - dask ==2023.3.1
  - minio ==7.1.14
  - simplekml ==1.3.6
  - python ==3.9.15
  - scandir ==1.10.0
  - pip:
     - nr-objstore-util==0.10.0
     - python-cmr==0.7.0
