FROM continuumio/miniconda3:4.9.2-alpine AS build

COPY requirements-conda.txt /requirements-conda.txt
RUN conda update -y conda && \
    conda config --add channels conda-forge && \
    conda config --add channels anaconda && \
    conda create -y --name process python=3.9 && \
    conda install -n process -y --file requirements-conda.txt

RUN conda install -c conda-forge conda-pack && \
    conda-pack -n process -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar && \
    /venv/bin/conda-unpack

FROM ubuntu:20.04 AS runtime
COPY --from=build /venv /venv

COPY hello.py /hello.py

SHELL ["/bin/bash", "-c"]
ENTRYPOINT source /venv/bin/activate && python hello.py
