name: Compute watershed average snow cover

on:
  # push:
  #   branches:
  #     - "main"
  schedule:
  # job should run at 9.01 pst which translates to 5pm UTC
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  compute_basin_averages:
    defaults:
      run:
        shell: bash
    name: 'Calculate basin averaged snow cover'
    runs-on: ubuntu-20.04
    environment: PROD
    env:
      OBJ_STORE_BUCKET: ${{ secrets.OBJ_STORE_BUCKET }}
      OBJ_STORE_SECRET: ${{ secrets.OBJ_STORE_SECRET }}
      OBJ_STORE_USER: ${{ secrets.OBJ_STORE_USER }}
      OBJ_STORE_HOST: ${{ secrets.OBJ_STORE_HOST }}

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
       fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - id: install_dependencies
      name: install python dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install -r requirements_tif2csv.txt

    - id: debug
      name: debug and list files
      shell: bash
      run: |
        ls -la

    - id: cloud_filling
      name: Produce cloud free images using most recent cloud free pixel
      shell: bash
      run: |
        python process/cloud_filling.py

    - id: compute_Basin_Averages
      name: Compute basin averaged snow cover fraction and upload to s3
      shell: bash
      run: |
        python process/tif2poly.py
